#!/usr/bin/python3

import os
import sys
import subprocess

def get_dir_name() -> str:
    result = subprocess.run(["ls | grep -e \"task_*_*\""],shell=True,stdout=subprocess.PIPE)
    return result.stdout.decode("utf-8").split()[0]


def default() -> None:
    os.system(
        f"tar -cvf ./{get_dir_name()}.tar.gz ./{get_dir_name()}/" 
    )


def exclude_input() -> None:
    os.system(
        f"tar -cvf ./{get_dir_name()}.tar.gz ./{get_dir_name()}/" \
        f"--exclude=./{get_dir_name()}/in.*"
    )


def show_help() -> None:
    print(
        """
        `compress` : a Python script to compress the LAMMPS output data into a `task_*_*.tar.gz` archive.

            - Dependencies : 
                - the Python virtual environment must have been activated either by the \
Makefile or the `venv/bin/activate` command

            - Flags : 
                - `--all` or `-a` or no flags : 
                    This results in compressing all the files in the `task_*_*` directory.
                - `--only-output` or `-o` :
                    This results in compressing all the files in the `task_*_*` directory \
output by LAMMPS.
        """
    )


def throw_error() -> None:
    print(
        f"\"{' '.join(sys.argv[1:])}\" is an invalid argument." \
        " Run \"./compress --help\" or \"./compress -h\" to see valid options"
    )


def main() -> None:
    try: 
        flag = sys.argv[1]
    except IndexError:
        default()
        exit()

    if flag in ["--all","-a"]:
        default()
    elif flag in ["--only-output","-o"]:
        exclude_input()
    elif flag in ["--help","-h"]:
        show_help()
    else:
        throw_error()

if __name__ == "__main__":
    main()

