#!/bin/bash

# array of file identifiers that are incomplete
unmatching=($(ls | grep -E "restart\.Bennu|dmp\.reg" | grep -Eo "(V[0-9]\.[0-9]+_A[0-9]+)" | sort | uniq -u))

# funtion to write the write the batch file
# TODO figure out how do line indents
function writeBatch(
{
echo '#!/bin/bash
#SBATCH -o out_straggler.log
#SBATCH -p standard
#SBATCH -t 120:00:00
#SBATCH -n 32
#SBATCH --mem-per-cpu=200M
echo Running on $SLURM_JOB_NODELIST
module load lammps/23Jun2022/b1
unsetr SLURM_GTIDS
lmp_mpi -in ./in.impact_Bennu_1x_'"${1}" > ./test_straggler_${2}.sbatch
}

# writing a separate .sbatch file for each straggler file
j=1
for i in "${unmatching[@]}"; do
    # TODO limit it at up to 8 parallel files even with more than 8 stragglers
    writeBatch $i $j
    j++((j++))
done
